### ISSUE TITLE
I don't get the warning

### ISSUE THREAD

**Issue by brunocalado** [BlitzKraig/fvtt-TrustIssues#3]
Hi,

I tried at 0.66/0.74 but I couldn't make it work. 

The player view open the devtools in another computer. 

I got this error:
```
DevTools failed to load SourceMap: Could not load content for http://MYIP:30000/modules/TrustIssues/trustissues.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

Thank you.

**Comment by BlitzKraig** [comment]
Hi brunocalado,

That error is standard, it just means I've not provided the mapping file for the minified source.

Your players devtools should have hit a forced breakpoint. If they try to continue, or close the devtools, it will then show you the error.
